services:
  postgres:
    image: postgres:latest
    container_name: bookstore-postgres
    environment:
      POSTGRES_USER: yousefwmorsy
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookstore
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: