spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: BookStore
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-minutes: 15
  refresh-token-expiration-days: 7